import React, {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/All.module.css'
import wavy from '../wavy.png'
import wavy2 from '../waves2.svg'
import {motion} from 'framer-motion'
import About from '../components/About'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import Web3 from '../components/Web3'

export default function Home() {
  const [nav, setNav] = useState('About')
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /><link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet"></link>
        <script src='https://cdn.jsdelivr.net/npm/kute.js@2.1.2/dist/kute.min.js'></script>
      </Head>
      <nav className={styles.nav}>
        <ul>
          <li onClick={() => setNav('About')}>About</li>
          <li onClick={() => setNav('Contact')}>Contact</li>
          <li onClick={() => setNav('Projects')}>Projects</li>
        </ul>
      </nav>
      <div className={styles.hero}>
        <h1>Welcome</h1>
        <h1>To My</h1>
        <h1>My Portfolio</h1>
      </div>
      {(nav == 'About') ?
      <About />
      :
      (nav == 'Projects') ?
      <Projects />
      :
      (nav == 'Contact') ? 
      <Contact />
      :
      (nav == 'Web3') ?
      <Web3 />
      :
      ''
      }

    </div>
  )
}
